# Generated by Django 3.2.5 on 2021-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im1', models.ImageField(upload_to='', verbose_name='Каритнка слево')),
                ('im2', models.ImageField(upload_to='', verbose_name='Картинка справо')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Картинка 2в1',
                'verbose_name_plural': 'Картинки 2в1',
            },
        ),
    ]
