# Generated by Django 3.2.5 on 2021-07-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_rename_img_imagesmerge_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmerge',
            name='mask',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Маска:'),
        ),
        migrations.AlterField(
            model_name='imagesmerge',
            name='im1',
            field=models.ImageField(upload_to='', verbose_name='Каритнка справо'),
        ),
        migrations.AlterField(
            model_name='imagesmerge',
            name='im2',
            field=models.ImageField(upload_to='', verbose_name='Картинка слево'),
        ),
    ]
