# Generated by Django 3.2.5 on 2021-08-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_maskimg2img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmerge',
            name='masf_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comp.maskimg2img'),
        ),
    ]
