# Generated by Django 3.2.5 on 2021-08-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0005_imagesmerge_masf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesmerge',
            name='masf_file',
        ),
        migrations.AddField(
            model_name='imagesmerge',
            name='mask_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comp.maskimg2img', verbose_name='Шаблон маски'),
        ),
    ]
