# Generated by Django 3.2.5 on 2021-08-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_auto_20210801_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image2Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im1', models.ImageField(upload_to='img2img', verbose_name='Каритнка справо')),
                ('im2', models.ImageField(upload_to='img2img', verbose_name='Картинка слево')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img2img_result', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Merge to 2 image',
                'verbose_name_plural': 'Merges to 2 images',
            },
        ),
        migrations.AlterField(
            model_name='imagesmerge',
            name='im1',
            field=models.ImageField(upload_to='img2img', verbose_name='Каритнка справо'),
        ),
        migrations.AlterField(
            model_name='imagesmerge',
            name='im2',
            field=models.ImageField(upload_to='img2img', verbose_name='Картинка слево'),
        ),
        migrations.AlterField(
            model_name='imagesmerge',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img2img_result', verbose_name='Результат'),
        ),
    ]
