# Generated by Django 3.2.5 on 2021-08-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0007_auto_20210811_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='image2image',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Черный'), (125, 'Серый'), (255, 'Белый')], default=255, verbose_name='Цвет линии'),
            preserve_default=False,
        ),
    ]
